### PR TITLE
Refactoring error handling, auth, etc.

### PR DESCRIPTION
**Pull request by bsingr**
# Changes

- Cleanup error handling
- Cleanup auth
- Misc minor cleanups

# Statistics

- ~8% less lines of code
- added 1 src file
- added 1 test file

```
before

            Physical :  363
              Source :  314
             Comment :  2
 Single-line comment :  2
       Block comment :  0
               Mixed :  2
               Empty :  49

Number of files read :  13

------------------------------

after

            Physical :  336
              Source :  289
             Comment :  2
 Single-line comment :  2
       Block comment :  0
               Mixed :  2
               Empty :  47

Number of files read :  14
```

### CODE REVIEW

**Comment by kuddl** [comment]
👍

**Comment by kuddl** [comment]
double 👍 for using sloc 😸

**Comment by jotaen** [comment]
@kuddl Please stop spamming. I’m awaiting your pull request with a mongoose refactoring.

@bsingr I’m still not sure about your errorHandler approach. It’s more elegant, but it also increases complexity, of which I’m not sure that it really adds value here.

**Comment by jotaen** [comment]
@bsingr Thanks for pointing several things out. I adopted some of your improvements in #8 . However, I decided on keeping the old error handling approach for the above-mentioned reasons.

**Pull request closed without merging**
